name: Create and publish a container image

on:
  schedule:
    - cron: "30 20 * * Wed"
  push:
    branches: 
      - 'master'
    tags:
      - 'v*.*.*'
env:
  REGISTRY: ghcr.io
  REPO_ORG: reliq-hq
  IMAGE_NAME: comfyui

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta-xpu
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.REPO_ORG }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            prefix=xpu-
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push Docker image for Intel XPU
        id: push-xpu
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: Dockerfile.xpu
          tags: ${{ steps.meta-xpu.outputs.tags }}
          labels: ${{ steps.meta-xpu.outputs.labels }}
